<script setup lang="ts">
import { computed, ref } from 'vue'
import schematic from '@/assets/capacitor-network.svg'
import { calculateEquivalentCapacitance, solveMissingCapacitance, type CapacitorNetworkMode } from '@/calculators/capacitance'
interface Row { id: number; enabled: boolean; value: string | number; factor: number }
const mode = ref<CapacitorNetworkMode>('parallel'); const target = ref<'total'|'missing'>('total'); const result = ref<number|null>(null); const error = ref(''); const targetTotal = ref(''); const targetFactor = ref(1e-12); let nextId=4
const rows=ref<Row[]>([{id:1,enabled:true,value:'',factor:1e-12},{id:2,enabled:true,value:'',factor:1e-12},{id:3,enabled:true,value:'',factor:1e-12}])
const units=[{label:'pF',factor:1e-12},{label:'nF',factor:1e-9},{label:'μF',factor:1e-6},{label:'mF',factor:1e-3},{label:'F',factor:1}]
const formula=computed(()=>mode.value==='parallel'?'CT = C1 + C2 + … + Cn':'1 / CT = 1 / C1 + 1 / C2 + … + 1 / Cn')
const allSelected=computed(()=>rows.value.every(row=>row.enabled)); const selectedCount=computed(()=>rows.value.filter(row=>row.enabled).length)
function clearResult():void{result.value=null;error.value=''}
function switchMode(value:CapacitorNetworkMode):void{mode.value=value;clearResult()}
function addRows(count:number):void{for(let i=0;i<count&&rows.value.length<100;i+=1)rows.value.push({id:nextId++,enabled:true,value:'',factor:1e-12});clearResult()}
function remove(id:number):void{if(rows.value.length>2)rows.value=rows.value.filter(row=>row.id!==id);clearResult()}
function toggleAll():void{const next=!allSelected.value;rows.value.forEach(row=>{row.enabled=next});clearResult()}
function values():number[]{return rows.value.filter(row=>row.enabled&&String(row.value).trim()!=='').map(row=>Number(row.value)*row.factor)}
function calculate():void{error.value='';try{result.value=target.value==='total'?calculateEquivalentCapacitance(mode.value,values()):solveMissingCapacitance(mode.value,Number(targetTotal.value)*targetFactor.value,values())}catch(cause){result.value=null;error.value=cause instanceof Error?cause.message:String(cause)}}
function format(value:number):string{const unit=value>=1?units[4]:value>=1e-3?units[3]:value>=1e-6?units[2]:value>=1e-9?units[1]:units[0];return `${Number((value/unit.factor).toPrecision(9))} ${unit.label}`}
</script>
<template><section class="network-layout"><div class="panel network-controls"><div class="panel-toolbar"><div><h2>串并联电容计算器</h2><p>计算多个电容的等效值，或反算缺失电容 Cn</p></div><span class="circuit-type">{{ formula }}</span></div><div class="network-mode-tabs"><button :class="{active:mode==='parallel'}" @click="switchMode('parallel')">并联电容</button><button :class="{active:mode==='series'}" @click="switchMode('series')">串联电容</button></div><div class="solve-targets network-targets"><label :class="{active:target==='total'}"><input v-model="target" type="radio" value="total" @change="clearResult">求等效总电容</label><label :class="{active:target==='missing'}"><input v-model="target" type="radio" value="missing" @change="clearResult">反算缺失电容 Cn</label></div><label v-if="target==='missing'" class="network-total-field"><span>目标等效总电容 CT</span><div class="value-with-unit"><input v-model="targetTotal" type="number" min="0" step="any" @input="clearResult"><select v-model.number="targetFactor"><option v-for="unit in units" :key="unit.label" :value="unit.factor">{{ unit.label }}</option></select></div></label><div class="network-toolbar"><button class="soft-button" @click="toggleAll">{{ allSelected?'取消全选':'全选' }}</button><button class="soft-button" @click="addRows(1)">添加电容</button><button class="soft-button" @click="addRows(5)">添加 5 条</button><button class="soft-button" @click="rows.filter(r=>r.enabled).forEach(r=>r.value='');clearResult()">清空选中</button><span>已选 {{ selectedCount }} / {{ rows.length }}，最多 100 条</span></div><div class="resistor-list"><div v-for="(row,index) in rows" :key="row.id" class="resistor-row"><input v-model="row.enabled" type="checkbox" :aria-label="`选择 C${index+1}`"><strong>C{{ index+1 }}</strong><input v-model="row.value" type="number" min="0" step="any" :disabled="!row.enabled" :aria-label="`C${index+1} 容值`" placeholder="输入容值" @input="clearResult"><select v-model.number="row.factor" :disabled="!row.enabled" :aria-label="`C${index+1} 单位`"><option v-for="unit in units" :key="unit.label" :value="unit.factor">{{ unit.label }}</option></select><button class="row-delete" :disabled="rows.length<=2" @click="remove(row.id)">×</button></div></div><button class="wide-action" @click="calculate">{{ target==='total'?'计算等效总电容':'计算缺失电容 Cn' }}</button><p v-if="error" class="error-message">{{ error }}</p><div class="unified-result"><template v-if="result!==null"><span>{{ target==='total'?'等效总电容 CT':'缺失电容 Cn' }}</span><strong>{{ format(result) }}</strong><code>{{ formula }}</code></template><p v-else>空白行自动忽略；并联电容相加，串联电容按倒数和计算。</p></div></div><aside class="panel network-schematic-panel"><h2>{{ mode==='parallel'?'并联电容原理图':'串联电容关系' }}</h2><img :src="schematic" alt="并联电容原理图" :class="{ 'series-capacitor-image':mode==='series' }"><div class="netlist-check"><strong>{{ mode==='parallel'?'各支路电压相同':'各电容电荷量相同' }}</strong><p>{{ mode==='parallel'?'总电容等于各电容之和。':'总电容小于任意一个串联电容。' }}</p></div></aside></section></template>
