<script setup lang="ts">
import { ref } from 'vue'
import schematic from '@/assets/led-resistor.svg'
import { calculateLedResistor, type LedResistorResult } from '@/calculators/ledResistor'
import { useI18n } from '@/i18n'
const { tr } = useI18n()
const supply=ref('5'); const forward=ref('2'); const currentMa=ref('10'); const count=ref('1'); const result=ref<LedResistorResult|null>(null); const error=ref('')
function calculate():void{error.value='';try{result.value=calculateLedResistor(Number(supply.value),Number(forward.value),Number(currentMa.value)/1000,Number(count.value))}catch(cause){result.value=null;error.value=cause instanceof Error?cause.message:String(cause)}}
function resistance(value:number):string{return value>=1000?`${Number((value/1000).toPrecision(7))} kΩ`:`${Number(value.toPrecision(7))} Ω`}
function power(value:number):string{return value<1?`${Number((value*1000).toPrecision(7))} mW`:`${Number(value.toPrecision(7))} W`}
</script>
<template><section class="led-layout"><div class="panel"><div class="panel-toolbar"><div><h2>{{ tr('LED 串联电阻计算器', 'LED Series Resistor Calculator') }}</h2><p>{{ tr('支持一个或多个串联 LED，并推荐 E24 标准电阻与安全功率', 'Supports one or more series LEDs and recommends an E24 resistor and safe power rating') }}</p></div><span class="circuit-type">R = (VS - n × VF) / IF</span></div><div class="led-input-grid"><label><span>{{ tr('供电电压 VS', 'Supply Voltage VS') }}</span><div class="value-with-unit"><input v-model="supply" type="number" min="0" step="any"><span>V</span></div></label><label><span>{{ tr('单颗 LED 正向压降 VF', 'LED Forward Voltage VF') }}</span><div class="value-with-unit"><input v-model="forward" type="number" min="0" step="any"><span>V</span></div></label><label><span>{{ tr('目标正向电流 IF', 'Target Forward Current IF') }}</span><div class="value-with-unit"><input v-model="currentMa" type="number" min="0" step="any"><span>mA</span></div></label><label><span>{{ tr('串联 LED 数量 n', 'Number of Series LEDs n') }}</span><input v-model="count" type="number" min="1" max="100" step="1"></label></div><button class="wide-action" @click="calculate">{{ tr('计算限流电阻', 'Calculate Resistor') }}</button><p v-if="error" class="error-message">{{ error }}</p><div v-if="result" class="led-results"><div><span>{{ tr('理论电阻', 'Ideal Resistance') }}</span><strong>{{ resistance(result.resistance) }}</strong></div><div class="recommended"><span>{{ tr('推荐 E24 电阻', 'Recommended E24 Resistor') }}</span><strong>{{ resistance(result.recommendedResistance) }}</strong></div><div><span>{{ tr('推荐后的实际电流', 'Actual Current') }}</span><strong>{{ Number((result.actualCurrent*1000).toPrecision(7)) }} mA</strong></div><div><span>{{ tr('电阻实际功耗', 'Resistor Dissipation') }}</span><strong>{{ power(result.resistorPower) }}</strong></div><div><span>{{ tr('推荐电阻功率', 'Recommended Rating') }}</span><strong>≥ {{ result.recommendedPowerRating }} W</strong></div><div><span>{{ tr('LED 总功耗', 'Total LED Power') }}</span><strong>{{ power(result.ledPower) }}</strong></div></div><p class="load-note"><strong>{{ tr('选型建议：', 'Selection advice:') }}</strong>{{ tr('推荐电阻向上取标准阻值，使 LED 电流不超过目标值；电阻额定功率按实际功耗至少 2 倍选择。', 'Choose the next higher standard value so current does not exceed the target, and use at least twice the actual power dissipation.') }}</p></div><aside class="panel led-schematic-panel"><h2>{{ tr('LED 限流原理图', 'LED Current-Limiting Schematic') }}</h2><img :src="schematic" alt="LED schematic"><div class="netlist-check"><strong>{{ tr('连接顺序', 'Connection Order') }}</strong><p>VCC → LED Anode → LED Cathode → R → GND</p><p>{{ tr('多个 LED 串联时，正向压降按数量累加。', 'For series LEDs, forward voltage adds with LED count.') }}</p></div></aside></section></template>
